receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed
  awsxray:
    region: ap-southeast-1
  awsemf:
    region: ap-southeast-1

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - debug
        - awsxray
    metrics:
      receivers:
        - otlp
      exporters:
        - debug
        - awsemf
