receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  awsxray:
    region: ap-southeast-1
    endpoint: "https://vpce-075be96e13cf931d3-8b15tt0k.xray.ap-southeast-1.vpce.amazonaws.com"
    no_verify_ssl: false

  awsemf:
    region: ap-southeast-1

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - debug
        - awsxray
    metrics:
      receivers:
        - otlp
      exporters:
        - debug
        - awsemf
